import type { NextPage } from 'next'
import { Main } from 'next/document'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { Menu } from '../../src/component/Menu'
import { Login } from '../../src/component/Login'
import { MainBanner} from '../../src/component/MainBanner'
import { Model } from '../../src/component/Model'
import { Footer } from '../../src/component/Footer'
import { TradeIn } from '../../src/component/TradeIn'
import { SalesComponent } from '../../src/component/Sales'
import { SelectTest } from '../../src/component/selectTest'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'
import { useState } from 'react'
import BarMenu from '../../src/component/BarMenu'



const  Admin: NextPage = () => {
    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    return (
      <>
        <Head>
          <title>OPEL</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu />
        <BarMenu />
        <Login />
        
        {
          showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
        }
  
        {
         showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal}/>
        }
      </>
    )
  }
  
  export default Admin
  