import type { NextPage } from 'next'
import Head from 'next/head'
import { Menu } from '../../src/component/Menu'
import { Footer } from '../../src/component/Footer'
import BarMenu from '../../src/component/BarMenu'
import { BannerCargo} from '../../src/component/carsModels/ComboCargo/BannerCargo'
import { PurchaseMethods} from '../../src/component/carsModels/Zafira/PurchaseMethods'
import { TextCombo} from '../../src/component/carsModels/ComboCargo/textCombo'
import { Modal } from '../../src/component/Modal'
import { useState } from 'react'

const ComboCargoPage: NextPage = () => {
  const [showModal, setShowModal] = useState(false)
    return (
      <>
        <Head>
          <title>OPEL APKOHT Combo Cargo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Menu />
          <BarMenu />
          <BannerCargo setShowModal={setShowModal} />
          <PurchaseMethods setShowModal={setShowModal} />
          <TextCombo  setShowModal={setShowModal}  />
          <Footer  />
          {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }
     </>
    )
}




export default ComboCargoPage