import type { NextPage } from 'next'
import Head from 'next/head'
import { Menu } from '../../src/component/Menu'
import { Footer } from '../../src/component/Footer'
import BarMenu from '../../src/component/BarMenu'
import { BannerZafira } from '../../src/component/carsModels/Zafira/BannerZafira'
import { PurchaseMethods} from '../../src/component/carsModels/Zafira/PurchaseMethods'
import { TextZafira} from '../../src/component/carsModels/Zafira/textZafira'
import { Modal } from '../../src/component/Modal'
import { useState } from 'react'

const ZafiraPage: NextPage = () => {
  const [showModal, setShowModal] = useState(false)
    return (
      <>
        <Head>
          <title>OPEL APKOHT ZAFIRA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Menu />
          <BarMenu />
          <BannerZafira setShowModal={setShowModal} />
          <PurchaseMethods setShowModal={setShowModal} />
          <TextZafira setShowModal={setShowModal} />
          <Footer  />
          {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }
     </>
    )
}




export default ZafiraPage