import type { NextPage } from 'next'
import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import { Menu } from '../src/component/Menu'
import { Map} from '../src/component/Map'
import { Footer } from '../src/component/Footer'
import BarMenu from '../src/component/BarMenu'

const ModelPage: NextPage = () => {
    return (
      <>
        <Head>
          <title>OPEL APKOHT CONTACT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Menu />
          <BarMenu />
          <Map />
          <Footer />
     </>
    )
}




export default ModelPage