import type { NextPage } from 'next'
import { Main } from 'next/document'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { Menu } from '../src/component/Menu'
import { Login } from '../src/component/Login'
import { MainBanner } from '../src/component/MainBanner'
import { Model } from '../src/component/Model'
import { ModelBanner } from '../src/component/ModelBanner'
import { Footer } from '../src/component/Footer'
import { CarsMenu } from '../src/component/CarsMenu'
import { TradeIn } from '../src/component/TradeIn'
// import { handlerXml } from '/server/api/hello.js'
import { SelectTest } from '../src/component/selectTest'
import { useState } from 'react'
import { Modal } from '../src/component/Modal'
import BarMenu from '../src/component/BarMenu'

const ModelPage: NextPage = () => {
  const [showModal, setShowModal] = useState(false)
  return (
    <>
      <Head>
        <title>OPEL Model</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <BarMenu />
      <ModelBanner />
      <SelectTest setShowModal={setShowModal} />
      <TradeIn />
      <Footer />
      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }
    </>
  )
}
export default ModelPage