import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { Menu } from '../src/component/Menu'
import { ModelBanner } from '../src/component/ModelBanner'
import { ModelRow} from '../src/component/ModelRow'
import { Footer } from '../src/component/Footer'
import { TradeIn } from '../src/component/TradeIn'
// import { handlerXml } from '/server/api/hello.js'
import { SelectTest } from '../src/component/selectTest'
import { useState } from 'react'
import { Modal } from '../src/component/Modal'
import BarMenu from '../src/component/BarMenu'
import { TradeinModal } from '../src/component/ModalTwo'

const ModelPage: NextPage = () => {
  const [showModal, setShowModal] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  return (
    <>
      <Head>
        <title>OPEL Model</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <BarMenu />
      <ModelBanner />
      <ModelRow  setShowModal={setShowModal}/>
      <SelectTest setShowModal={setShowModal} />
      <TradeIn setShowTradeInModal={setShowTradeInModal} />
      <Footer />
      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }
      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }
    </>
  )
}
export default ModelPage